apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnk8s
  #namespace: cisco
  labels:
    app: ccp
spec:
  replicas: 2
  selector:
    matchLabels: 
        app: ccp
  template:
    metadata:
        labels:
            app: ccp
    spec:  
      containers:
      - name: learnk8s-container
        image: nettas/k8slearn:0.02